export enum ACTION_NAMES_ENUM {
  REMOVE_TODOLIST = "REMOVE_TODOLIST",
  REMOVE_TASK_FROM_LIST = "REMOVE_TASK_FROM_LIST",
  ADD_TODOLIST = "ADD_TODOLIST",
  ADD_TASK_IN_TODOLIST = "ADD_TASK_IN_TODOLIST",
  CHANGE_TODOLIST_TITLE = "CHANGE_TODOLIST_TITLE",
  CHANGE_TODOLIST_FILTER = "CHANGE_TODOLIST_FILTER",
  CHANGE_TASK_FROM_LIST_STATUS = "CHANGE_TASK_FROM_LIST_STATUS",
}
